
brandinfo = "https://opensheet.elk.sh/1qTdwMLDeH7sHGnf37KcMbf78TnNqYBAL28zVWKo_tds/BrandInfo"

[[pages]]
title = "Waterjets"
data = "https://opensheet.elk.sh/1qTdwMLDeH7sHGnf37KcMbf78TnNqYBAL28zVWKo_tds/Waterjets"

[[pages]]
title = "Transmissions"
data = "https://opensheet.elk.sh/1qTdwMLDeH7sHGnf37KcMbf78TnNqYBAL28zVWKo_tds/Transmissions"

[[pages]]
title = "Inboard Engines"
data = "https://opensheet.elk.sh/1qTdwMLDeH7sHGnf37KcMbf78TnNqYBAL28zVWKo_tds/Inboard"
desc = "If you are in need of an engine for your vessel, ADR's experienced sales professionals can guide you through the engine selection process to ensure optimal performance while complying with applicable regulations."

[[pages]]
title = "Outboard Engines"
data = "https://opensheet.elk.sh/1qTdwMLDeH7sHGnf37KcMbf78TnNqYBAL28zVWKo_tds/Outboard"

[[pages]]
title = "Generators"
data = "https://opensheet.elk.sh/1qTdwMLDeH7sHGnf37KcMbf78TnNqYBAL28zVWKo_tds/Generators"

[[pages]]
title = "Electronics"
data = "https://opensheet.elk.sh/1qTdwMLDeH7sHGnf37KcMbf78TnNqYBAL28zVWKo_tds/Electronics"